name: Reusable for CD

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      path:
        required: true
        type: string
      filename:
        required: true
        type: string
    secrets:
      ssh_priv_key:
        required: true
      dockerhub_token:
        required: true

jobs:
  Change-image-tag-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id  : vars
        run : |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "SHORT_SHA_OTHER=$calculatedSha" >> $GITHUB_ENV  

      - name: Set up Git
        run: |
          git config --global user.name 'Tereza'
          git config --global user.email 'an3146073@gmail.com'

      - name: Setup SSH
        uses: MrSquaare/ssh-setup-action@v1
        with:
          host: github.com
          private-key: ${{ secrets.ssh_priv_key }}
          private-key-name: github
          
      - name: Clone target repository
        run: git clone git@github.com:tereza-arta/k8s-manifests.git

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.31.2/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq   

      - name: Update YAML file with yq
        working-directory: k8s-manifests
        run: |
          yq '.spec.template.spec.containers.[0].image = "terezabisharyan/${{inputs.image}}:${{env.SHORT_SHA_OTHER}}"' -i ${{inputs.path}}/${{inputs.filename}}

      - name: Commit and Push Changes
        working-directory: k8s-manifests
        env:
          GITHUB_TOKEN: ${{ secrets.dockerhub_token }}
        run: |
          git add ${{inputs.path}}/${{inputs.filename}}
          git commit -m "Update image in k8s deployment"
          git push origin main       
